### ISSUE TITLE
Problem with Unpack

### ISSUE THREAD

**Issue by Mahantor** [blackeangel/UKA#1]
When I try to unpack the br file, I encounter this error
no such file or directory
I took pictures of the entire process. Please solve this problem.
![Screenshot_2023-03-17-22-12-33-679_com termux-edit](https://user-images.githubusercontent.com/91434001/225996528-d3f5dd2d-96fc-4c55-90e0-585572d661ab.jpg)
![Screenshot_2023-03-17-22-13-08-686_com termux-edit](https://user-images.githubusercontent.com/91434001/225996632-1580a292-ecc3-4e27-8c3b-56af53b8588a.jpg)
![Screenshot_2023-03-17-22-15-42-504_bin mt plus-edit](https://user-images.githubusercontent.com/91434001/225996848-f8e51a70-853f-4125-aced-e2a7f62faf13.jpg)
![Screenshot_2023-03-17-22-13-30-179_com termux-edit](https://user-images.githubusercontent.com/91434001/225997150-e67585ea-6d09-4332-9cb5-ba67c96492df.jpg)

OR

![Screenshot_2023-03-17-22-15-07-885_com termux-edit](https://user-images.githubusercontent.com/91434001/225997882-047b8f79-d579-405f-a57f-9b4578fe6a9e.jpg)
![Screenshot_2023-03-17-22-13-53-593_com termux-edit](https://user-images.githubusercontent.com/91434001/225998033-8609ba95-f5c5-4d73-b195-41f1555942c6.jpg)
![Screenshot_2023-03-17-22-14-18-256_com termux-edit](https://user-images.githubusercontent.com/91434001/225998171-260f19dc-df06-48b0-a893-65629e86f34a.jpg)

**Comment by blackeangel** [comment]
> When I try to unpack the br file, I encounter this error no such file or directory I took pictures of the entire process. Please solve this problem. ![Screenshot_2023-03-17-22-12-33-679_com termux-edit](https://user-images.githubusercontent.com/91434001/225996528-d3f5dd2d-96fc-4c55-90e0-585572d661ab.jpg) ![Screenshot_2023-03-17-22-13-08-686_com termux-edit](https://user-images.githubusercontent.com/91434001/225996632-1580a292-ecc3-4e27-8c3b-56af53b8588a.jpg) ![Screenshot_2023-03-17-22-15-42-504_bin mt plus-edit](https://user-images.githubusercontent.com/91434001/225996848-f8e51a70-853f-4125-aced-e2a7f62faf13.jpg) ![Screenshot_2023-03-17-22-13-30-179_com termux-edit](https://user-images.githubusercontent.com/91434001/225997150-e67585ea-6d09-4332-9cb5-ba67c96492df.jpg)
> 
> OR
> 
> ![Screenshot_2023-03-17-22-15-07-885_com termux-edit](https://user-images.githubusercontent.com/91434001/225997882-047b8f79-d579-405f-a57f-9b4578fe6a9e.jpg) ![Screenshot_2023-03-17-22-13-53-593_com termux-edit](https://user-images.githubusercontent.com/91434001/225998033-8609ba95-f5c5-4d73-b195-41f1555942c6.jpg) ![Screenshot_2023-03-17-22-14-18-256_com termux-edit](https://user-images.githubusercontent.com/91434001/225998171-260f19dc-df06-48b0-a893-65629e86f34a.jpg)

What version did you install? When did you download the archive?

**Comment by Mahantor** [comment]
And some people have this problem with super.img
![Screenshot_2023-03-17-22-44-18-736_com kiwibrowser browser-edit](https://user-images.githubusercontent.com/91434001/225999578-df3f6b91-e08e-4d8d-b4e9-ef5d37bab1b3.jpg)

**Comment by blackeangel** [comment]
> And some people have this problem with super.img ![Screenshot_2023-03-17-22-44-18-736_com kiwibrowser browser-edit](https://user-images.githubusercontent.com/91434001/225999578-df3f6b91-e08e-4d8d-b4e9-ef5d37bab1b3.jpg)

hmm.. strange, i thought i fixed it....at least i have .br, .new.dat, .img files unpacking....

**Comment by Mahantor** [comment]
> 

V5.18

**Comment by blackeangel** [comment]
> > 
> 
> V5.18

Yes of course
