### ISSUE TITLE
Problems With m_menu Scripts

### ISSUE THREAD

**Issue by zxrovx** [blackeangel/UKA#3]
![Screenshot_20230831-080901945](https://github.com/blackeangel/UKA/assets/91070944/ffdf60ca-74eb-4608-ab1f-7374772a53ac)

**Comment by zxrovx** [comment]
That's Latest Version 5.22

**Comment by Werve** [comment]
I confirm, same error. But the files exist in their respective paths.
Someone on xda said 5.19 doesn't show this error.

**Comment by johnt1989** [comment]
Same error hmm.

**Comment by Werve** [comment]
5.21 seems work.
So maybe the redirect/invocation of the file menu -> m_menu is not always allowed?

**Comment by blackeangel** [comment]
> 5.21 seems work.
> So maybe the redirect/invocation of the file menu -> m_menu is not always allowed?

I know about this error. Most likely this is due to the fact that everything was done on Windows, and some error in text formatting or something like that could occur.

**Comment by blackeangel** [comment]
Fixed. Download UKA_522_fix.zip (https://github.com/blackeangel/UKA/releases/download/522/UKA_522_fix.zip) from release page https://github.com/blackeangel/UKA/releases/tag/522
Clean install.
