### ISSUE TITLE
Calling the wrong python version

### ISSUE THREAD

**Issue by johnt1989** [blackeangel/UKA#4]
Using the 5.22 fixes version

bin/easy_install:python39 /data/local/python39/usr/bin/easy_install "$@"
install.sh:#unzip -p "$ZIPFILE" "python39.tar.xz" |tar xJ -C /data/local >/dev/null
local/binary/a_atr:      read ab && aa=$(python39 $binary_dir/atrib.py "$ab")
local/binary/a_atr:      read ac && bb=$(python39 $binary_dir/atrib.py "$ac")
local/binary/ker_ver:  #python39 "$dir_ver"/bin_system/find_gz.py "$file" "1f8b08"
local/binary/m_menu:              #python39 /data/local/binary/bin_oppo_decrypt/ofp_mtk_decrypt.py "$file" "$m_name" 1> log.txt
local/binary/m_menu:              #python39 /data/local/binary/bin_oppo_decrypt/ofp_qc_decrypt.py "$file" /"$ofp_dir"/"$m_name" 1>> log.txt
local/binary/rem_key:    #offset_avb="$(python39 /data/local/binary/bin_system/find_avb0.py "$file" "41564230" | busybox head -1)"
local/binary/unpack_img:        #python39 /data/local/binary/bin_system/find_avb.py "$file_avb" "41564230000000" "$dir_avb"

Edit trying too make it easier too read

**Comment by blackeangel** [comment]
Fixed. Download UKA_522_fix_1.zip (https://github.com/blackeangel/UKA/releases/download/522/UKA_522_fix_1.zip) from release page https://github.com/blackeangel/UKA/releases/tag/522
Clean install.
